import { test, expect, start, navigate, travelTo } from './helpers.js'

test('phone utilities, chapter navigation and closing remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  await start(page, 'alex-manager', 'team-performance', 'reduce', false)
  await page.getByLabel('Open notifications').click()
  const panel = page.locator('.notification-panel')
  await expect(panel).toBeVisible()
  const bounds = await panel.boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(320)
  const before = await page.locator('.is-front .paper-layer').getAttribute('data-progress')
  await panel.hover()
  await page.mouse.wheel(0, 800)
  expect(await page.locator('.is-front .paper-layer').getAttribute('data-progress')).toBe(before)
  await page.keyboard.press('Escape')
  await page.getByLabel('Search the book').click()
  await page.getByRole('combobox', { name: 'Search ChampionsClub' }).fill('missing entry')
  await expect(page.locator('.search-empty')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByLabel('Search the book').click()
  await navigate(page, 'closing', false)
  await page.keyboard.press('End')
  await page.getByRole('button', { name: 'Close Book', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'The book is closed' })).toBeVisible()
  await page.getByRole('button', { name: 'Open book', exact: true }).click()
  await expect(page.locator('.book-intro')).toHaveCount(0)
})

test('chart focus is a sharp portal with contextual data and one blurred backdrop', async ({ page }) => {
  await start(page, 'alex-manager', 'forecasts', 'reduce', false)
  await travelTo(page, .25)
  const point = page.locator('.is-front').getByRole('button', { name: 'Sep 30: €438,000', exact: true })
  await point.focus()
  await point.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Forecast detail / Sep 30' })
  await expect(dialog).toBeVisible()
  await expect(dialog.locator('.chart-detail-copy')).toContainText('84%')
  await expect(dialog.locator('.chart-detail-copy')).toContainText('+€18,000')
  expect(await dialog.evaluate((element) => getComputedStyle(element, '::backdrop').backdropFilter)).toBe('blur(12px)')
  expect(await dialog.evaluate((element) => getComputedStyle(element).filter)).toBe('none')
  await page.screenshot({ path: 'artifacts/reader-chart-focus.png' })
  const before = await page.locator('.is-front .paper-layer').getAttribute('data-progress')
  await dialog.hover()
  await page.mouse.wheel(0, 500)
  expect(await page.locator('.is-front .paper-layer').getAttribute('data-progress')).toBe(before)
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(point).toBeFocused()
})

test('rapid direct navigation cannot commit a stale route', async ({ page }) => {
  await start(page, 'alex-manager', 'team-performance', 'no-preference', false)
  await page.getByRole('link', { name: 'Rewards', exact: true }).click()
  await page.evaluate(() => { location.hash = '/targets' })
  await expect(page.locator('.publication')).toHaveAttribute('data-route', 'targets')
  await expect(page).toHaveURL('http://127.0.0.1:5173/#/targets')
})

