import { test, expect } from '@playwright/test'
import { readFileSync, existsSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { money, number, localDate } from '../src/lib/format.js'

const settingsFile = fileURLToPath(new URL('../../../.work/preview-settings.json', import.meta.url))
const local = existsSync(settingsFile) ? JSON.parse(readFileSync(settingsFile, 'utf8').trim()) : {}
const password = process.env.CHAMPIONSCLUB_DEMO_PASSWORD || local.password
const apiBase = process.env.PLAYWRIGHT_API_BASE_URL || local.api || 'http://127.0.0.1:8080'
const advisorEmail = process.env.CHAMPIONSCLUB_TEST_ADVISOR || 'jane.doe@championsclub.example'
const managerEmail = process.env.CHAMPIONSCLUB_TEST_MANAGER || 'alex.smith@championsclub.example'
const canMutate = process.env.CHAMPIONSCLUB_ALLOW_TEST_MUTATIONS === '1'
const artifacts = fileURLToPath(new URL('../artifacts/premium/', import.meta.url))
mkdirSync(artifacts, { recursive: true })

test.beforeAll(() => { if (!password) throw new Error('Set CHAMPIONSCLUB_DEMO_PASSWORD and a dedicated verification backend before running live tests.') })

async function apiLogin(request, email) {
  const response = await request.post(`${apiBase}/api/auth/login`, { data: { email, password } })
  expect(response.status()).toBe(200)
  return response.json()
}
async function get(request, auth, path) {
  const response = await request.get(`${apiBase}${path}`, { headers: { Authorization: `Bearer ${auth.accessToken}` } })
  expect(response.status()).toBe(200)
  return response.json()
}
async function login(page, email = advisorEmail) {
  await page.goto('/')
  await page.getByLabel('Email address', { exact: false }).fill(email)
  await page.getByLabel('Password', { exact: false }).fill(password)
  const response = page.waitForResponse(response => response.url().endsWith('/api/auth/login') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const result = await response
  expect(result.status()).toBe(200)
  await expect(page.getByRole('heading', { name: 'Welcome back,', exact: false })).toBeVisible()
  await expect(page.locator('.kpi').first()).toBeVisible()
  return result.json()
}
async function navigate(page, title) {
  await page.locator('.sidebar nav').getByRole('link', { name: title, exact: true }).click()
  await expect(page.locator('main')).not.toContainText('This view could not be displayed')
}
async function screenshot(page, name) {
  await page.screenshot({ path: `${artifacts}${name}.png`, fullPage: true })
}

test('advisor login, truthful overview metrics, navigation, date filters, charts and logout', async ({ page, request }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  const auth = await login(page)
  const dashboard = await get(request, auth, `/api/dashboard/advisor/${auth.user.id}`)
  const kpis = page.locator('.kpi')
  await expect(kpis.nth(0)).toContainText(money(dashboard.performance.analytics.sales))
  await expect(kpis.nth(1)).toContainText(number(dashboard.performance.analytics.recordedContracts))
  await expect(kpis.nth(3)).toContainText(number(dashboard.performance.availablePoints))
  await expect(page.locator('.sidebar')).not.toContainText('Your team')
  await expect(page.locator('video,canvas')).toHaveCount(0)
  await screenshot(page, 'advisor-overview')
  await navigate(page, 'Performance')
  await page.getByLabel('From', { exact: true }).fill('2026-08-01')
  await page.getByLabel('To', { exact: true }).fill('2026-08-31')
  await page.getByRole('button', { name: 'Apply dates' }).click()
  const analytics = await get(request, auth, `/api/analytics?subjectId=${auth.user.id}&subjectType=ADVISOR&start=2026-08-01&end=2026-08-31`)
  await expect(page.locator('.kpi').first()).toContainText(money(analytics.sales))
  await page.getByLabel('Chart interval').selectOption('weeklySales')
  await page.getByRole('button', { name: 'View data table' }).click()
  await expect(page.getByRole('table', { name: 'Recorded contract value' })).toBeVisible()
  await expect(page.getByRole('table', { name: 'Recorded contract value' }).locator('tbody tr')).toHaveCount(analytics.weeklySales.length)
  await page.getByLabel('Breakdown dimension').selectOption('customerSegmentMix')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export report' }).click()
  expect((await download).suggestedFilename()).toContain('2026-08-01')
  await screenshot(page, 'advisor-analytics')
  await navigate(page, 'Targets')
  await expect(page.getByRole('heading', { name: 'My targets' })).toBeVisible()
  await expect(page.locator('.target-summary')).toContainText(money(dashboard.performance.target.progress.targetAmount))
  await expect(page.getByRole('button', { name: 'Set target' })).toHaveCount(0)
  await navigate(page, 'Insights')
  await expect(page.getByText('Rules-based performance brief', { exact: true })).toBeVisible()
  await expect(page.locator('.insight-lead')).toContainText(dashboard.insight.result.summary)
  await page.goto('/#/advisors')
  await expect(page.getByRole('heading', { name: 'This page is not available' })).toBeVisible()
  await page.locator('.sidebar').getByRole('button', { name: 'Sign out' }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  const revoked = await request.get(`${apiBase}/api/me`, { headers: { Authorization: `Bearer ${auth.accessToken}` } })
  expect(revoked.status()).toBe(401)
  expect(errors).toEqual([])
})

test('real sales creation, conflict handling, cancellation, filters and pagination', async ({ page, request }) => {
  test.skip(!canMutate, 'Explicitly enable mutations against a dedicated verification database.')
  const auth = await login(page)
  const before = await get(request, auth, `/api/points/${auth.user.id}`)
  await navigate(page, 'Sales activity')
  await page.getByRole('button', { name: 'Record a sale', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.locator('summary').click()
  await dialog.getByRole('button', { name: 'Classic Financing', exact: true }).click()
  await dialog.getByLabel('Contract value (EUR)', { exact: false }).fill('1500.25')
  const reference = `UI-VERIFY-${Date.now()}`
  await dialog.getByLabel('External reference', { exact: false }).fill(reference)
  await screenshot(page, 'sale-form')
  const response = page.waitForResponse(response => response.url().endsWith('/api/sales') && response.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Record sale', exact: true }).click()
  const created = await response
  expect(created.status()).toBe(201)
  const sale = await created.json()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('row').filter({ hasText: reference })).toBeVisible()
  const after = await get(request, auth, `/api/points/${auth.user.id}`)
  expect(after.availablePoints).toBe(before.availablePoints + sale.awardedPoints)
  await page.getByRole('button', { name: 'Record a sale', exact: true }).click()
  await dialog.locator('summary').click()
  await dialog.getByRole('button', { name: 'Classic Financing', exact: true }).click()
  await dialog.getByLabel('Contract value (EUR)', { exact: false }).fill('1500.25')
  await dialog.getByLabel('External reference', { exact: false }).fill(reference)
  await dialog.getByRole('button', { name: 'Record sale', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('already exists')
  await expect(dialog.getByLabel('External reference', { exact: false })).toHaveValue(reference)
  await dialog.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('row').filter({ hasText: reference }).getByRole('button', { name: 'Cancel sale' }).click()
  await expect(dialog.getByRole('heading', { name: 'Cancel this sale?' })).toBeVisible()
  await screenshot(page, 'cancel-confirmation')
  await dialog.getByRole('button', { name: 'Confirm cancellation' }).click()
  await expect(page.getByRole('row').filter({ hasText: reference })).toContainText('Cancelled')
  const reverted = await get(request, auth, `/api/points/${auth.user.id}`)
  expect(reverted.availablePoints).toBe(before.availablePoints)
  await page.getByLabel('Status', { exact: true }).selectOption('CANCELLED')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.locator('tbody .badge').first()).toHaveText('Cancelled')
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await page.getByRole('button', { name: 'Next page' }).click()
  await expect(page.locator('.pagination')).toContainText('Page 2')
  await screenshot(page, 'sales-table')
})

test('real reward redemption issues voucher and invalidates balance', async ({ page, request }) => {
  test.skip(!canMutate, 'Explicitly enable mutations against a dedicated verification database.')
  const auth = await login(page)
  const before = await get(request, auth, `/api/points/${auth.user.id}`)
  await navigate(page, 'Rewards')
  await expect(page.locator('.reward-card').first()).toBeVisible()
  await screenshot(page, 'rewards')
  await page.getByRole('button', { name: 'Redeem reward', exact: true }).first().click()
  const response = page.waitForResponse(response => response.url().endsWith('/api/rewards/redemptions') && response.request().method() === 'POST')
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm redemption' }).click()
  const confirmed = await response
  expect(confirmed.status()).toBe(201)
  const receipt = await confirmed.json()
  await expect(page.getByRole('dialog')).toContainText(receipt.voucherCode)
  const after = await get(request, auth, `/api/points/${auth.user.id}`)
  expect(after.availablePoints).toBe(before.availablePoints - receipt.redeemedPoints)
  expect(after.lifetimeEarnedPoints).toBe(before.lifetimeEarnedPoints)
  await page.getByRole('button', { name: 'View redemption history' }).click()
  await expect(page.getByRole('table')).toContainText(receipt.voucherCode)
})

test('manager directory, drill-down, target management and audited point adjustment', async ({ page, request }) => {
  test.skip(!canMutate, 'Explicitly enable mutations against a dedicated verification database.')
  const auth = await login(page, managerEmail)
  const data = await get(request, auth, `/api/dashboard/manager/${auth.user.id}/dealership/${auth.user.dealershipId}`)
  await expect(page.locator('.kpi').first()).toContainText(money(data.performance.analytics.sales))
  await expect(page.locator('.sidebar')).not.toContainText('Points ledger')
  await screenshot(page, 'manager-overview')
  await navigate(page, 'Your team')
  await page.getByRole('textbox', { name: 'Search advisors' }).fill('Jane')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByRole('link', { name: 'View advisor' }).click()
  await expect(page.getByRole('heading', { name: 'Jane Doe', exact: true })).toBeVisible()
  const profileId = page.url().split('/advisors/')[1].split('?')[0]
  await screenshot(page, 'advisor-detail')
  await page.getByRole('button', { name: 'Targets', exact: true }).click()
  await page.getByRole('button', { name: 'Set target', exact: true }).click()
  const dialog = page.getByRole('dialog')
  const start = new Date(2030, 0, 1 + Math.floor(Date.now() / 1000) % 300)
  const targetDate = localDate(start)
  await dialog.getByLabel('Start date', { exact: false }).fill(targetDate)
  await dialog.getByLabel('End date', { exact: false }).fill(targetDate)
  await dialog.getByLabel('Target value (EUR)', { exact: false }).fill('22000')
  await dialog.getByLabel('Status', { exact: true }).selectOption('false')
  const createdResponse = page.waitForResponse(response => response.url().endsWith('/api/targets') && response.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Create target' }).click()
  expect((await createdResponse).status()).toBe(201)
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: 'Edit target' }).first().click()
  await dialog.getByLabel('Target value (EUR)', { exact: false }).fill('23000')
  await dialog.getByRole('button', { name: 'Save target' }).click()
  await expect(page.getByRole('table')).toContainText('€23,000')
  await page.getByRole('button', { name: 'Points', exact: true }).click()
  const before = await get(request, auth, `/api/points/${profileId}`)
  await page.getByRole('button', { name: 'Adjust points' }).click()
  await dialog.getByLabel('Point adjustment', { exact: false }).fill('17')
  await dialog.getByLabel('Reason', { exact: false }).fill('Isolated browser verification adjustment')
  await dialog.getByRole('button', { name: 'Confirm adjustment' }).click()
  await expect(dialog).not.toBeVisible()
  const after = await get(request, auth, `/api/points/${profileId}`)
  expect(after.availablePoints).toBe(before.availablePoints + 17)
  await expect(page.getByRole('table')).toContainText('Isolated browser verification adjustment')
})

test('trained forecasts, manager refresh and backend authorization boundaries', async ({ page, request }) => {
  const auth = await login(page, managerEmail)
  await navigate(page, 'Forecasts')
  await page.getByRole('button', { name: 'Refresh forecast', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Forecasted daily sales' })).toBeVisible()
  const forecast = await get(request, auth, `/api/forecasts?subjectId=${auth.user.dealershipId}&subjectType=DEALERSHIP`)
  expect(forecast.state).toBe('AVAILABLE')
  expect(forecast.result.modelVersion.startsWith('snapshot-selected')).toBeTruthy()
  await expect(page.locator('.kpi').first()).toContainText(money(forecast.result.predictedEndValue))
  await screenshot(page, 'manager-forecast')
  await navigate(page, 'Leaderboard')
  await page.getByLabel('Advisor cohort').selectOption('SERVICE')
  await expect(page.getByRole('table')).toContainText('Service advisor')
  const advisor = await apiLogin(request, advisorEmail)
  for (const path of ['/api/advisors', '/api/dashboard/advisor/7', '/api/dashboard/manager/1/dealership/2']) {
    const response = await request.get(`${apiBase}${path}`, { headers: { Authorization: `Bearer ${advisor.accessToken}` } })
    expect(response.status()).toBe(403)
  }
  const admin = await request.get(`${apiBase}/api/admin/users`, { headers: { Authorization: `Bearer ${auth.accessToken}` } })
  expect(admin.status()).toBe(404)
})

test('service error, empty results, session expiry and keyboard modal behavior', async ({ page }) => {
  await login(page)
  await page.route('**/api/products?**', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Provider unavailable' }) }))
  await navigate(page, 'Product catalog')
  await expect(page.getByRole('alert')).toContainText('The service could not complete this request')
  await page.unroute('**/api/products?**')
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByRole('table')).toBeVisible()
  await page.getByRole('button', { name: 'View details' }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'View details' }).first()).toBeFocused()
  await page.getByRole('textbox', { name: 'Search products' }).fill('NO-PRODUCT-WITH-THIS-NAME')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'No products found' })).toBeVisible()
  await screenshot(page, 'empty-state')
  await page.route('**/api/alerts?**', route => route.fulfill({ status: 401, contentType: 'application/json', body: JSON.stringify({ message: 'Access denied.' }) }))
  await navigate(page, 'Notifications')
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  await expect(page.getByRole('status')).toContainText('Your session has expired')
})

for (const width of [1440, 1280, 768, 390]) {
  test(`responsive overview, analytics, rewards and tables at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await login(page)
    for (const route of ['overview', 'performance', 'sales', 'rewards']) {
      await page.goto(`/#/${route}`)
      await expect(page.locator('main h1')).toBeVisible()
      await expect(page.locator('.loading-state')).toHaveCount(0)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
      await screenshot(page, `${route}-${width}`)
    }
    if (width < 760) {
      await page.getByRole('button', { name: 'Open navigation' }).click()
      await expect(page.getByRole('dialog')).toBeVisible()
      await page.getByRole('dialog').getByRole('link', { name: 'Targets', exact: true }).click()
      await expect(page.getByRole('heading', { name: 'My targets' })).toBeVisible()
      await expect(page.getByRole('dialog')).not.toBeVisible()
    }
  })
}
