import { test, expect, start } from './helpers.js'

test('Escape releases a held corner and wheel over the corner still turns the sheet', async ({ page }) => {
  await start(page, 'alex-manager', 'team-performance', 'no-preference', false)
  await page.keyboard.press('End')
  await expect(page.locator('.publication')).toHaveAttribute('data-edge', 'end')
  const corner = page.getByRole('button', { name: 'Pull bottom-right corner toward top-left to turn page' })
  await corner.focus()
  await page.mouse.move(1400, 965)
  await page.mouse.down()
  await page.mouse.move(950, 620, { steps: 10 })
  await expect(page.locator('.publication')).toHaveAttribute('data-mode', 'DRAGGING_CORNER')
  await page.keyboard.press('Escape')
  expect(await page.locator('.publication').getAttribute('data-mode')).toBe('SETTLING')
  await page.mouse.up()
  await expect(page.locator('.publication')).toHaveAttribute('data-mode', 'AT_PAGE_END')
  await page.waitForTimeout(500)
  await page.mouse.move(1410, 970)
  await page.mouse.wheel(0, 120)
  await page.waitForTimeout(250)
  await page.mouse.wheel(0, 180)
  await expect(page.locator('.publication')).toHaveAttribute('data-mode', 'CURLING_WITH_SCROLL')
  await page.keyboard.press('Escape')
  await expect(page.locator('.publication')).toHaveAttribute('data-mode', 'AT_PAGE_END')
  await expect(page.locator('.publication')).toHaveAttribute('data-route', 'team-performance')
})

test('browser Back unfolds the previous sheet even when its chapter number is higher', async ({ page }) => {
  await start(page, 'alex-manager', 'team-performance', 'no-preference', false)
  await page.getByRole('link', { name: 'Executive Overview', exact: true }).click()
  await expect(page.locator('.publication')).toHaveAttribute('data-route', 'overview')
  await page.waitForTimeout(350)
  await page.goBack()
  await expect(page.locator('.publication')).toHaveAttribute('data-mode', 'NAVIGATING_DIRECTLY')
  expect(await page.locator('.publication').getAttribute('data-turn-direction')).toBe('backward')
  expect(await page.locator('.is-front .paper-layer').getAttribute('data-sheet')).toBe('team-performance')
  await expect(page.locator('.publication')).toHaveAttribute('data-route', 'team-performance')
})

test('touch scroll stays inside the working page while the camera remains still', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, reducedMotion: 'reduce' })
  const page = await context.newPage()
  await start(page, 'alex-manager', 'targets')
  const workspace = page.locator('.is-front .local-workspace')
  expect(await workspace.evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  const progress = await page.locator('.is-front .paper-layer').getAttribute('data-progress')
  const session = await context.newCDPSession(page)
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 190, y: 615 }] })
  for (const y of [585, 550, 500, 450, 400, 350]) {
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 190, y }] })
    await page.waitForTimeout(30)
  }
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  expect(await workspace.evaluate((element) => element.scrollTop)).toBeGreaterThan(60)
  await expect(page.locator('.is-front .paper-layer')).toHaveAttribute('data-progress', progress)
  await context.close()
})

test('the closing sheet can turn back and advisor detail continues to the next chapter', async ({ page }) => {
  await start(page, 'alex-manager', 'closing', 'reduce', false)
  await page.mouse.move(45, 750)
  await page.mouse.wheel(0, -120)
  await expect(page.locator('.publication')).toHaveAttribute('data-route', 'profile')
  await page.goto('/?boundary=advisor#/advisor-detail/3')
  await expect(page.locator('.publication')).toHaveAttribute('data-route', 'advisor-detail/3')
  await page.keyboard.press('End')
  await page.mouse.wheel(0, 120)
  await page.waitForTimeout(230)
  await page.mouse.wheel(0, 120)
  await expect(page.locator('.is-under .paper-layer')).toHaveAttribute('data-sheet', 'targets')
  for (let step = 0; step < 13; step += 1) { await page.mouse.wheel(0, 180); await page.waitForTimeout(30) }
  await expect(page.locator('.publication')).toHaveAttribute('data-route', 'targets')
})

test('utility panels dismiss on Escape and release their focus', async ({ page }) => {
  await start(page)
  await page.getByLabel('Search the book').click()
  await page.getByRole('combobox', { name: 'Search ChampionsClub' }).fill('Jane')
  await page.keyboard.press('Escape')
  await expect(page.locator('.editorial-index')).not.toHaveAttribute('open')
  await expect(page.getByLabel('Search the book')).toBeFocused()
  await page.getByLabel('Choose demo account').click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.ownership-mark')).not.toHaveAttribute('open')
})
