import { test, expect, start, navigate, state, enterWorking, changeAccount, travelTo } from './helpers.js'

test('a new sale persists and updates performance, points and targets', async ({ page }) => {
  await start(page, 'alex-manager', 'dealership-activity')
  await page.getByRole('button', { name: 'Record sale', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('combobox', { name: 'Advisor', exact: true }).selectOption('1')
  await dialog.getByRole('combobox', { name: 'Product', exact: true }).selectOption('Classic Financing')
  await dialog.getByLabel('Amount', { exact: true }).fill('10000')
  await dialog.getByLabel('Date', { exact: true }).fill('2026-09-10')
  await dialog.getByRole('button', { name: 'Record sale', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  const saved = await state(page)
  expect(saved.dealership.monthlySales).toBe(322400)
  expect(saved.advisors[0].points).toBe(1450)
  expect(saved.targets.find((target) => target.advisorId === 1).actual).toBe(128500)
  await page.reload()
  await enterWorking(page)
  await page.getByLabel('Search sales').fill('Classic')
  await expect(page.locator('.is-front .premium-table-row')).toHaveCount(2)
  await page.getByLabel('Search sales').fill('no matching sales')
  await expect(page.locator('.is-front .premium-table-row')).toHaveCount(0)
  await page.getByLabel('Search sales').fill('')
  await page.getByLabel('Filter product').selectOption('Service Protection')
  await expect(page.locator('.is-front .premium-table-row')).toHaveCount(2)
  await page.getByLabel('Filter product').selectOption('All')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.locator('.is-front .pagination')).toContainText('Page 2 of 2')
})

test('advisor sales and form scrolling respect identity and camera position', async ({ page }) => {
  await start(page, 'jane-advisor', 'sales-history')
  await expect(page.locator('.is-front .premium-table-row')).toHaveCount(2)
  await page.getByRole('button', { name: 'Record sale', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('combobox', { name: 'Advisor', exact: true }).locator('option')).toHaveCount(1)
  await dialog.getByLabel('Amount', { exact: true }).fill('-1')
  await dialog.getByRole('button', { name: 'Record sale' }).click()
  await expect(dialog).toBeVisible()
  const before = await page.locator('.is-front .paper-layer').getAttribute('data-progress')
  await dialog.hover()
  await page.mouse.wheel(0, 15000)
  expect(await page.locator('.is-front .paper-layer').getAttribute('data-progress')).toBe(before)
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Record sale', exact: true })).toBeFocused()
})

test('target create, edit and persistence retain advisor permissions', async ({ page }) => {
  await start(page, 'alex-manager', 'targets')
  await page.getByRole('button', { name: 'Create target' }).click()
  await page.getByLabel('Target name').fill('Quarter-end ambition')
  await page.getByLabel('Target amount').fill('99000')
  await page.getByRole('button', { name: 'Save target' }).click()
  await expect(page.locator('.is-front .target-card')).toHaveCount(5)
  await page.locator('.is-front .target-card').filter({ hasText: 'Quarter-end ambition' }).getByRole('button').click()
  await page.getByLabel('Target amount').fill('110000')
  await page.getByRole('button', { name: 'Save target' }).click()
  await page.reload()
  await enterWorking(page)
  await expect(page.locator('.is-front .target-card').filter({ hasText: 'Quarter-end ambition' })).toContainText('€110,000')
  await changeAccount(page, 'jane-advisor')
  await navigate(page, 'targets')
  await expect(page.getByRole('button', { name: 'Create target' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Edit target' })).toHaveCount(0)
})

test('catalogue redemption deducts once, preserves lifetime membership and filters rewards', async ({ page }) => {
  await start(page, 'jane-advisor', 'rewards')
  await travelTo(page, .5)
  const redeem = page.getByRole('button', { name: 'Redeem reward', exact: true })
  await redeem.click()
  await expect(page.getByRole('dialog')).toContainText('680')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await redeem.click()
  await page.getByRole('button', { name: 'Confirm redemption' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const saved = await state(page)
  expect(saved.advisors[0].points).toBe(1330)
  expect(saved.advisors[0].availablePoints).toBe(680)
  expect(saved.redemptions.filter((item) => item.status === 'Submitted')).toHaveLength(1)
  await expect(page.getByRole('button', { name: 'Redemption submitted' })).toBeDisabled()
  await page.getByRole('button', { name: 'Travel', exact: true }).click()
  await expect(page.locator('.is-front .catalogue-presentation')).toContainText('Sustainable Travel Voucher')
  await expect(page.getByRole('button', { name: 'Keep building your balance' })).toBeDisabled()
  await page.screenshot({ path: 'artifacts/reader-catalogue.png' })
})

test('forecast scenarios, reviewed alerts and intelligence actions work', async ({ page }) => {
  await start(page, 'alex-manager', 'forecasts')
  await travelTo(page, .625)
  await page.getByRole('button', { name: 'Conservative', exact: true }).click()
  await expect(page.locator('.is-front [data-scene="5"] .print-amount')).toContainText('394,200')
  await page.getByRole('button', { name: 'Stretch', exact: true }).click()
  await expect(page.locator('.is-front [data-scene="5"] .print-amount')).toContainText('473,040')
  await navigate(page, 'alerts')
  await page.locator('.is-front .alert-card button').first().click()
  await expect(page.locator('.is-front .alert-card.is-reviewed')).toHaveCount(1)
  await page.getByLabel('Filter alert severity').selectOption('WARNING')
  await expect(page.locator('.is-front .alert-card')).toHaveCount(2)
  await navigate(page, 'ai-insights')
  await travelTo(page, 5 / 6)
  await page.locator('.is-front .printed-actions button').first().click()
  await expect(page.locator('.is-front .printed-actions button').first()).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.locator('.is-front .printed-actions button').first()).toHaveAttribute('aria-pressed', 'true')
})

test('ranking sorting and advisor details retain meaningful routes', async ({ page }) => {
  await start(page, 'alex-manager', 'leaderboard')
  await page.getByRole('region', { name: 'The championship', exact: true }).getByRole('button', { name: 'Points', exact: true }).click()
  await expect(page.locator('.is-front .champion-scene h2')).toContainText('Alex')
  await travelTo(page, .25)
  await page.getByRole('button', { name: 'View performance', exact: true }).click()
  await expect(page.locator('.publication')).toHaveAttribute('data-route', 'advisor-detail/3')
  await enterWorking(page)
  await expect(page.locator('.is-front .profile-hero')).toContainText('Alex Smith')
})

test('account preferences remain independent across navigation and reload', async ({ page }) => {
  await start(page, 'alex-manager', 'profile')
  await page.getByRole('button', { name: 'Edit preferences' }).click()
  await page.getByRole('combobox', { name: 'Notification digest', exact: true }).selectOption('Weekly')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await page.reload()
  await enterWorking(page)
  await expect(page.locator('.is-front .local-workspace')).toContainText('Weekly')
  await changeAccount(page, 'jane-advisor')
  await navigate(page, 'profile')
  await expect(page.locator('.is-front .profile-hero')).toContainText('Jane Doe')
  await expect(page.locator('.is-front .local-workspace')).toContainText('Daily')
})
