import { test, expect, start, navigate, state } from './helpers.js'

test('a new sale persists and updates performance, points and targets', async ({ page }) => {
  await start(page, 'alex-manager', 'dealership-activity')
  await page.getByRole('button', { name: 'Record sale', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await dialog.getByRole('combobox', { name: 'Advisor', exact: true }).selectOption('1')
  await dialog.getByRole('combobox', { name: 'Product', exact: true }).selectOption('Classic Financing')
  await dialog.getByLabel('Amount', { exact: true }).fill('10000')
  await dialog.getByLabel('Date', { exact: true }).fill('2026-09-10')
  await dialog.getByRole('button', { name: 'Record sale', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('status')).toContainText('Sale recorded')
  const saved = await state(page)
  expect(saved.dealership.monthlySales).toBe(322400)
  expect(saved.advisors[0].points).toBe(1450)
  expect(saved.targets.find((target) => target.advisorId === 1).actual).toBe(128500)
  await page.reload()
  await page.getByLabel('Search sales').fill('Classic')
  await expect(page.locator('.premium-table-row')).toHaveCount(2)
  await page.getByLabel('Search sales').fill('no matching sales')
  await expect(page.locator('.premium-table-row')).toHaveCount(0)
  await page.getByLabel('Search sales').fill('')
  await page.getByLabel('Filter product').selectOption('Service Protection')
  await expect(page.locator('.premium-table-row')).toHaveCount(2)
  await page.getByLabel('Filter product').selectOption('All')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.locator('.pagination')).toContainText('Page 2 of 2')
  await expect(page.getByRole('button', { name: 'Next', exact: true })).toBeDisabled()
})

test('advisor recording restricts the advisor and validates the amount', async ({ page }) => {
  await start(page, 'jane-advisor', 'sales-history')
  await expect(page.locator('.premium-table-row')).toHaveCount(2)
  await page.getByRole('button', { name: 'Record sale', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('combobox', { name: 'Advisor', exact: true }).locator('option')).toHaveCount(1)
  await page.getByRole('dialog').getByLabel('Amount', { exact: true }).fill('-1')
  await page.getByRole('dialog').getByRole('button', { name: 'Record sale' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.getByLabel('Amount', { exact: true }).evaluate((element) => element.validity.valid)).toBe(false)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Record sale', exact: true })).toBeFocused()
})

test('targets create, edit and persist while advisors cannot edit them', async ({ page }) => {
  await start(page, 'alex-manager', 'targets')
  await page.getByRole('button', { name: 'Create target' }).click()
  await page.getByLabel('Target name').fill('Quarter-end ambition')
  await page.getByLabel('Target amount').fill('99000')
  await page.getByRole('button', { name: 'Save target' }).click()
  await expect(page.locator('.target-card')).toHaveCount(5)
  await page.locator('.target-card').filter({ hasText: 'Quarter-end ambition' }).getByRole('button').click()
  await page.getByLabel('Target amount').fill('110000')
  await page.getByRole('button', { name: 'Save target' }).click()
  await page.reload()
  await expect(page.locator('.target-card').filter({ hasText: 'Quarter-end ambition' })).toContainText('€110,000')
  await page.getByLabel('Demo account switcher').selectOption('jane-advisor')
  await navigate(page, 'targets')
  await expect(page.getByRole('button', { name: 'Create target' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Edit target' })).toHaveCount(0)
})

test('reward redemption deducts once and preserves lifetime membership', async ({ page }) => {
  await start(page, 'jane-advisor', 'rewards')
  const fuel = page.locator('.reward-card').filter({ hasText: 'Premium Fuel Voucher' })
  await fuel.getByRole('button').click()
  await expect(page.getByRole('dialog')).toContainText('680')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.locator('.membership-balance')).toContainText('1,330')
  await fuel.getByRole('button').click()
  await page.getByRole('button', { name: 'Confirm redemption' }).dblclick()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.membership-balance')).toContainText('680')
  await expect(fuel.getByRole('button')).toBeDisabled()
  const saved = await state(page)
  expect(saved.advisors[0].points).toBe(1330)
  expect(saved.advisors[0].availablePoints).toBe(680)
  expect(saved.redemptions.filter((item) => item.status === 'Submitted')).toHaveLength(1)
  await page.getByRole('button', { name: 'Travel', exact: true }).click()
  await expect(page.locator('.reward-card')).toHaveCount(1)
  await expect(page.locator('.reward-card button')).toBeDisabled()
  await page.reload()
  await expect(page.locator('.membership-balance')).toContainText('680')
})

test('manager reward recipient, forecast scenarios, alerts and action plan work', async ({ page }) => {
  await start(page, 'alex-manager', 'rewards')
  await page.getByLabel('Reward advisor').selectOption('3')
  await expect(page.locator('.membership-card')).toContainText('Alex Smith')
  await expect(page.locator('.membership-balance')).toContainText('2,370')
  await navigate(page, 'forecasts')
  await page.getByRole('button', { name: 'Conservative', exact: true }).click()
  await expect(page.locator('.forecast-numbers')).toContainText('€394,200')
  await page.getByRole('button', { name: 'Stretch', exact: true }).click()
  await expect(page.locator('.forecast-numbers')).toContainText('€473,040')
  await page.locator('.chart-hit').first().focus()
  await expect(page.locator('.chart-tooltip')).toBeVisible()
  await page.getByRole('button', { name: 'Review active signals' }).click()
  await page.locator('.alert-card button').first().click()
  await expect(page.locator('.alert-card.is-reviewed')).toHaveCount(1)
  await page.getByLabel('Filter alert severity').selectOption('WARNING')
  await expect(page.locator('.alert-card')).toHaveCount(2)
  await page.getByLabel('Open notifications').click()
  await expect(page.locator('.notification-panel')).toBeVisible()
  await page.getByLabel('Close notifications').click()
  await navigate(page, 'ai-insights')
  await page.locator('.action-plan-row').first().click()
  await expect(page.locator('.action-plan-row').first()).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.locator('.action-plan-row').first()).toHaveAttribute('aria-pressed', 'true')
  await page.locator('.action-plan-row').first().click()
  await expect(page.locator('.action-plan-row').first()).toHaveAttribute('aria-pressed', 'false')
})

test('account preferences remain independent across navigation and reload', async ({ page }) => {
  await start(page, 'alex-manager', 'profile')
  await page.getByRole('button', { name: 'Edit preferences' }).click()
  await page.getByRole('combobox', { name: 'Notification digest', exact: true }).selectOption('Weekly')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await page.reload()
  await expect(page.locator('#workspace-content')).toContainText('Weekly')
  await page.getByLabel('Demo account switcher').selectOption('jane-advisor')
  await navigate(page, 'profile')
  await expect(page.locator('.profile-hero')).toContainText('Jane Doe')
  await expect(page.locator('#workspace-content')).toContainText('Daily')
})

