import { test, expect, start, navigate, state, changeAccount, travelTo } from './helpers.js'
import { chapterFrames } from '../src/experience/arteonTimeline.js'

test('a recorded sale persists and updates the cinematic performance data', async ({ page }) => {
  await start(page, 'alex-manager', 'dealership-activity')
  await page.getByRole('button', { name: 'Record sale', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('combobox', { name: 'Advisor', exact: true }).selectOption('1')
  await dialog.getByRole('combobox', { name: 'Product', exact: true }).selectOption('Classic Financing')
  await dialog.getByLabel('Amount', { exact: true }).fill('10000')
  await dialog.getByLabel('Date', { exact: true }).fill('2026-09-17')
  await dialog.getByRole('button', { name: 'Record sale', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  const saved = await state(page)
  expect(saved.dealership.monthlySales).toBe(322400)
  expect(saved.advisors[0].points).toBe(1450)
  expect(saved.targets.find((target) => target.advisorId === 1).actual).toBe(128500)
  await page.reload()
  await page.getByLabel('Search sales').fill('Classic')
  await expect(page.locator('.premium-table-row')).toHaveCount(2)
  await page.getByRole('button', { name: 'EXPERIENCE', exact: true }).click()
  await expect(page.locator('.experience-loading')).toHaveCount(0, { timeout: 20000 })
  await travelTo(page, chapterFrames[4] / 239)
  await expect(page.locator('.story-panel-4')).toBeVisible()
  await expect(page.locator('.story-panel-4')).toContainText('€322,400')
})

test('target creation and editing retain advisor permissions', async ({ page }) => {
  await start(page, 'alex-manager', 'targets')
  await page.getByRole('button', { name: 'Create target' }).click()
  await page.getByLabel('Target name').fill('Quarter-end ambition')
  await page.getByLabel('Target amount').fill('99000')
  await page.getByRole('button', { name: 'Save target' }).click()
  await expect(page.locator('.target-card')).toHaveCount(5)
  await page.locator('.target-card').filter({ hasText: 'Quarter-end ambition' }).getByRole('button').click()
  await page.getByLabel('Target amount').fill('110000')
  await page.getByRole('button', { name: 'Save target' }).click()
  await page.reload()
  await expect(page.locator('.target-card').filter({ hasText: 'Quarter-end ambition' })).toContainText('€110,000')
  await changeAccount(page, 'jane-advisor')
  await navigate(page, 'targets')
  await expect(page.getByRole('button', { name: 'Create target' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Edit target' })).toHaveCount(0)
})

test('redemption deducts available points once and preserves lifetime membership', async ({ page }) => {
  await start(page, 'jane-advisor', 'rewards')
  const redeem = page.getByRole('button', { name: 'Redeem reward', exact: true }).first()
  await redeem.click()
  await expect(page.getByRole('dialog')).toContainText('680')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await redeem.click()
  await page.getByRole('button', { name: 'Confirm redemption' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const saved = await state(page)
  expect(saved.advisors[0].points).toBe(1330)
  expect(saved.advisors[0].availablePoints).toBe(680)
  expect(saved.redemptions.filter((item) => item.status === 'Submitted')).toHaveLength(1)
  await expect(page.getByRole('button', { name: 'Redemption submitted' })).toBeDisabled()
  await page.getByRole('button', { name: 'Travel', exact: true }).click()
  await expect(page.locator('.reward-card')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Keep building your balance' })).toBeDisabled()
})

test('forecast scenarios, reviewed alerts and intelligence actions work', async ({ page }) => {
  await start(page, 'alex-manager', 'forecasts')
  await page.getByRole('button', { name: 'Conservative', exact: true }).click()
  await expect(page.locator('.forecast-numbers')).toContainText('394,200')
  await expect(page.locator('.forecast-confidence')).toContainText('Unavailable')
  await page.getByRole('button', { name: 'Stretch', exact: true }).click()
  await expect(page.locator('.forecast-numbers')).toContainText('473,040')
  await navigate(page, 'alerts')
  await page.locator('.alert-card button').first().click()
  await expect(page.locator('.alert-card.is-reviewed')).toHaveCount(1)
  await navigate(page, 'ai-insights')
  await page.locator('.next-actions button').first().click()
  await expect(page.locator('.next-actions button').first()).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.locator('.next-actions button').first()).toHaveAttribute('aria-pressed', 'true')
})

test('account preferences and role routes remain independent', async ({ page }) => {
  await start(page, 'alex-manager', 'profile')
  await page.getByRole('button', { name: 'Edit preferences' }).click()
  await page.getByRole('combobox', { name: 'Notification digest', exact: true }).selectOption('Weekly')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await page.reload()
  await expect(page.locator('#workspace-content')).toContainText('Weekly')
  await changeAccount(page, 'jane-advisor')
  await navigate(page, 'profile')
  await expect(page.locator('.profile-hero')).toContainText('Jane Doe')
  await expect(page.locator('#workspace-content')).toContainText('Daily')
  await page.evaluate(() => { location.hash = '/workspace/admin-users' })
  await expect(page.locator('.operational-workspace')).toHaveAttribute('data-route', 'overview')
  await expect(page.getByRole('button', { name: 'Users', exact: true })).toHaveCount(0)
  await changeAccount(page, 'john-admin')
  await expect(page.locator('.operational-workspace')).toHaveAttribute('data-route', 'admin-overview')
  await expect(page.getByRole('button', { name: 'Users', exact: true })).toHaveCount(1)
})
