import { useState } from 'react'
import { ArrowUpRight } from 'lucide-react'
import { ForecastChart } from '../../components/charts/ForecastChart.jsx'
import { formatCurrency } from '../../product/formatters.js'
import { Scene, JourneyOpening, PrintLabel, ChapterEnd } from './EditorialParts.jsx'

export function ForecastChapter({ data, stops, onNavigate }) {
  const [scenario, setScenario] = useState('Expected')
  const factor = scenario === 'Conservative' ? .9 : scenario === 'Stretch' ? 1.08 : 1
  const predicted = Math.round(data.forecast.predictedSales * factor)
  const actual = data.dealership.monthlySales
  const target = data.dealership.monthlyTarget
  return <>
    <Scene stops={stops} index={0}><JourneyOpening title="Forecasts / the road ahead" first="See the finish." emphasis="Shape the outcome." description="Travel from the history you know to the possibilities ahead. The future is a range, shaped by what you do next." /><div className="horizon-engraving" aria-hidden="true"><i /><i /><i /><i /><span>PAST — PRESENT — POSSIBLE</span></div></Scene>
    <Scene stops={stops} index={1} end={2} className="forecast-panorama"><PrintLabel number="01—02">ACTUAL HISTORY → CURRENT PERIOD → FORECAST</PrintLabel><div className="panorama-heading"><h2>The shape<br /><em>of possibility.</em></h2><span>THE FUTURE BEGINS HERE ↗<strong>{formatCurrency(predicted)}</strong></span></div><ForecastChart actual={actual} predicted={predicted} target={target} history={data.charts.monthlySales} confidence={data.forecast.confidence} /><p className="source-note">{data.forecastSource === 'live' ? 'SERVICE FORECAST / DEMO HISTORICAL CONTEXT' : 'DEMONSTRATION SERIES'} · SELECT A POINT TO EXAMINE IT</p></Scene>
    <Scene stops={stops} index={3}><PrintLabel number="03">WHERE WE STAND</PrintLabel><h2>Today's pace.<br /><em>Tomorrow's possibility.</em></h2><div className="print-amount"><span>€</span>{actual.toLocaleString('en')}</div><div className="volume-baseline"><span>CURRENT ACTUAL</span><span className="print-growth">{Math.round(actual / target * 100)}%<small>of the monthly target</small></span></div></Scene>
    <Scene stops={stops} index={4}><PrintLabel number="04">THE CONFIDENCE TO ACT</PrintLabel><h2>Probability.<br /><em>With perspective.</em></h2><div className="probability-print"><strong>{Math.round(data.forecast.targetAchievementProbability * 100)}<small>%</small></strong><p>Target achievement probability<br /><span>Expected scenario / model output</span></p></div><div className="volume-baseline"><span>MODEL CONFIDENCE</span><span>{Math.round(data.forecast.confidence * 100)}% / {data.forecast.modelQuality}</span></div><p className="editorial-note">The shaded chart region illustrates sensitivity of ±12%.<br />It is not a calibrated prediction interval.</p></Scene>
    <Scene stops={stops} index={5}><PrintLabel number="05">THE PROJECTED FINISH</PrintLabel><h2>One horizon.<br /><em>Several possibilities.</em></h2><div className="segmented-control print-scenarios" aria-label="Forecast scenario">{['Conservative', 'Expected', 'Stretch'].map((item) => <button key={item} aria-pressed={scenario === item} onClick={() => setScenario(item)}>{item}</button>)}</div><div className="print-amount"><span>€</span>{predicted.toLocaleString('en')}</div><p className="chapter-deck">{formatCurrency(Math.abs(predicted - target))} {predicted >= target ? 'above' : 'below'} the {formatCurrency(target)} target.</p><span className="source-note">{scenario === 'Expected' ? 'EXPECTED MODEL OUTPUT' : `ILLUSTRATIVE SCENARIO / ${factor === .9 ? '−10%' : '+8%'} FROM EXPECTED`}</span></Scene>
    <Scene stops={stops} index={6}><PrintLabel number="06">BEHIND THE PROJECTION</PrintLabel><h2>A forecast is only<br /><em>as strong as its signals.</em></h2><ol className="printed-enumeration">{data.forecast.assumptions.map((item) => <li key={item}>{item}</li>)}</ol><p className="editorial-note">Scenario adjustments are illustrative. Model confidence and probability remain tied to the expected forecast.</p></Scene>
    <Scene stops={stops} index={7} className="annotation-scene"><PrintLabel number="07">CHAMPIONS INTELLIGENCE / INTERPRETATION</PrintLabel><blockquote>{data.aiInsights.summary}</blockquote><div className="printed-risk">{data.forecast.anomalyHints.map((hint) => <p key={hint}>{hint}</p>)}</div><button className="print-link" onClick={() => onNavigate('alerts')}>Review the active signals<ArrowUpRight /></button></Scene>
    <Scene stops={stops} index={8}><ChapterEnd title="The future needs you." onNavigate={onNavigate} destination="ai-insights" nextTitle="Act on the intelligence">{data.aiInsights.nextActions[0]}</ChapterEnd></Scene>
  </>
}
